### ISSUE TITLE
使用android studio3打开后rebuild project接着run后运行出错，android4.4.2

### ISSUE THREAD

**Issue by yinjiaoyuan** [wildcreek/AppRTC-Android#1]
12/01 09:15:31: Launching app
$ adb push D:\yin\sample\cdn\webrtc\github\wildcreek\AppRTC-Android-master\app\build\outputs\apk\debug\app-debug.apk /data/local/tmp/org.appspot.apprtc
$ adb shell pm install -t -r "/data/local/tmp/org.appspot.apprtc"
	pkg: /data/local/tmp/org.appspot.apprtc
Success

$ adb shell am start -n "org.appspot.apprtc/org.appspot.apprtc.ConnectActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 6521 on device hisilicon-hi3796mv100-192.168.2.2:5555
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
D/AndroidRuntime: Shutting down VM
W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x2c82eba8)
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: org.appspot.apprtc, PID: 6521
                  java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{org.appspot.apprtc/org.appspot.apprtc.ConnectActivity}: java.lang.ClassNotFoundException: Didn't find class "org.appspot.apprtc.ConnectActivity" on path: DexPathList[[zip file "/data/app/org.appspot.apprtc-1.apk"],nativeLibraryDirectories=[/data/app-lib/org.appspot.apprtc-1, /vendor/lib, /system/lib]]
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2121)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
                      at android.app.ActivityThread.access$800(ActivityThread.java:135)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:136)
                      at android.app.ActivityThread.main(ActivityThread.java:5030)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:515)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                      at dalvik.system.NativeStart.main(Native Method)
                   Caused by: java.lang.ClassNotFoundException: Didn't find class "org.appspot.apprtc.ConnectActivity" on path: DexPathList[[zip file "/data/app/org.appspot.apprtc-1.apk"],nativeLibraryDirectories=[/data/app-lib/org.appspot.apprtc-1, /vendor/lib, /system/lib]]
                      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
                      at android.app.Instrumentation.newActivity(Instrumentation.java:1061)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2112)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
                      at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:136) 
                      at android.app.ActivityThread.main(ActivityThread.java:5030) 
                      at java.lang.reflect.Method.invokeNative(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:515) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                      at dalvik.system.NativeStart.main(Native Method) 
Application terminated.

**Comment by yinjiaoyuan** [comment]
我分析了一下，发现编译出来的apk生成了classes.dex和classes2.dex，这个功能是android5.0版本才开始支持的，我把multiDexEnabled改为false就可以正常运行了。
